### ISSUE TITLE
[issue] Start9 Logo is barely visible Day/Light Mode + low quality image

### ISSUE THREAD

**Issue by k0gen** [Start9Labs/searxng-startos#10]
<img width="922" alt="Screenshot 2023-01-02 at 14 40 54" src="https://user-images.githubusercontent.com/3606313/210239096-aeafb932-b37c-446f-81ff-8a228e3a8da3.png">

**Comment by 13Homer13** [comment]
I agree

**Comment by k0gen** [comment]
No longer relevant
