### ISSUE TITLE
[bug]: Re-install freezes at the end of the unpacking stage

### ISSUE THREAD

**Issue by islandbitcoin** [Start9Labs/searxng-startos#3]
### Prerequisites

- [X] I have searched for existing issues that already report this problem.

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

Ventura

### Browser

Firefox

### Browser Version

104.3

### Current Behavior

On reinstalling while the service is running, the install script freezes at the end of unpacking.

### Expected Behavior

Instal should complete as expected.

### Steps to Reproduce

1. Install Service.
2. Start Service.
3. Side-load Service again to reinstall.

### Anything else?

Reinstalling from the marketplace seems to work fine, only *sideloading* reproduces this error.

**Comment by islandbitcoin** [comment]
@dr-bonez could this be an eOS issue?

**Comment by k0gen** [comment]
fixed
